import React, { createContext, useContext, useState } from 'react';

interface LanguageContextType {
  currentLanguage: string;
  setLanguage: (languageCode: string) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};

const translations = {
  en: {
    'guest_review_manager': 'Guest Review Manager',
    'home': 'Home',
    'reviews': 'Reviews',
    'settings': 'Settings',
    'contact': 'Contact',
    'sign_out': 'Sign Out',
    'error_signing_out': 'Error signing out',
    'signed_out_successfully': 'Signed out successfully',
    'logged_out_message': 'You have been logged out.',
    'contact_title': 'Contact us for inquiries, support and partnership opportunities',
    'hotel_group_name': 'Hotel / Group Name',
    'enter_hotel_name': 'Enter your Hotel or Group Name',
    'full_name': 'Full Name',
    'enter_full_name': 'Enter full name',
    'email': 'Email',
    'enter_work_email': 'Enter your work Email',
    'work_phone': 'Work Phone',
    'enter_work_phone': 'Enter your work phone number',
    'message': 'Message',
    'enter_message': 'Enter your message...',
    'contact_us': 'Contact Us',
    'representative_offices': 'Reach out to our representative offices worldwide',
    'message_sent': 'Message Sent',
    'message_sent_description': "Thank you for contacting us. We'll get back to you soon!",
    // Dashboard
    'dashboard_title': 'Guest Review Dashboard',
    'dashboard_subtitle': 'Overview of your recent guest reviews and performance',
    'total_reviews': 'Total Reviews',
    'average_rating': 'Average Rating',
    'pending_replies': 'Pending Replies',
    'platform_distribution': 'Platform Distribution',
    'recent_reviews': 'Recent Reviews',
    'view_all_reviews': 'View all reviews',
    // Reviews
    'reviews_title': 'Guest Reviews',
    'reviews_subtitle': 'Manage and respond to all your guest reviews',
    'search_reviews': 'Search reviews...',
    'filter_by_platform': 'Filter by platform',
    'filter_by_rating': 'Filter by rating',
    'all_platforms': 'All platforms',
    'all_ratings': 'All ratings',
    'reply': 'Reply',
    'replied': 'Replied',
    // Analytics
    'analytics_title': 'Analytics',
    'analytics_subtitle': 'Insights and trends from your guest reviews',
    'review_trends': 'Review Trends',
    'rating_distribution': 'Rating Distribution',
    'sentiment_analysis': 'Sentiment Analysis',
    'keyword_analysis': 'Keyword Analysis',
    'positive_keywords': 'Most Mentioned Positive Keywords',
    'negative_keywords': 'Most Mentioned Negative Keywords',
    'positive': 'Positive',
    'negative': 'Negative',
    'neutral': 'Neutral',
    // Settings
    'settings_title': 'Settings',
    'settings_subtitle': 'Manage your account and platform integrations',
    'notification_settings': 'Notification Settings',
    'new_reviews': 'New reviews',
    'low_ratings': 'Low ratings (3 stars or below)',
    'reply_reminders': 'Reply reminders',
    'weekly_reports': 'Weekly summary reports',
    'connect': 'Connect',
    'disconnect': 'Disconnect',
    'last_sync': 'Last sync',
    'never': 'Never',
    'connected': 'Connected',
    'not_connected': 'Not connected',
    // Login
    'sign_in': 'Sign In',
    'sign_up': 'Sign Up',
    'create_account': 'Create your account',
    'welcome_back': 'Welcome back',
    'sign_in_to_account': 'Sign in to your account',
    'password': 'Password',
    'confirm_password': 'Confirm Password',
    'first_name': 'First Name',
    'last_name': 'Last Name',
    'business_name': 'Business Name',
    'optional': 'Optional',
    'have_account': 'Already have an account?',
    'no_account': "Don't have an account?",
    'sign_up_here': 'Sign up here',
    'sign_in_here': 'Sign in here',
    // Integrations
    'platform_integrations': 'Platform Integrations',
    'connect_review_platforms': 'Connect your review platforms to automatically import guest reviews.',
    'google_reviews': 'Google Reviews',
    'api_available': 'API Available',
    'google_reviews_description': 'Connect to Google Places API to automatically fetch reviews for your business location.',
    'google_api_key': 'Google Places API Key',
    'enter_google_api_key': 'Enter your Google Places API key',
    'place_id': 'Place ID',
    'enter_place_id': 'Enter your Google Place ID (e.g., ChIJN1t_tDeuEmsRUsoyG83frY4)',
    'find_place_id_text': 'Find your Place ID using the',
    'google_place_id_finder': 'Google Place ID Finder',
    'fetching_reviews': 'Fetching Reviews...',
    'fetch_google_reviews': 'Fetch Google Reviews',
    'booking_reviews': 'Booking.com Reviews',
    'manual_import': 'Manual Import',
    'booking_description': 'Booking.com doesn\'t provide public APIs. Upload your reviews manually using CSV import.',
    'no_api_access': 'No API Access:',
    'booking_restrictions': 'Booking.com restricts review data access to official partners only. Web scraping violates their Terms of Service and may result in legal action.',
    'upload_booking_csv': 'Upload Booking.com Reviews (CSV)',
    'csv_format_expected': 'Expected format: guest_name, date, rating, review_text',
    'importing': 'Importing...',
    'import_csv_file': 'Import CSV File',
    'airbnb_reviews': 'Airbnb Reviews',
    'airbnb_description': 'Airbnb discontinued their public API. Use manual import or CSV upload from your host dashboard.',
    'api_discontinued': 'API Discontinued:',
    'airbnb_restrictions': 'Airbnb shut down their public API in 2017. Manual data export from your host dashboard is the only legitimate option.',
    'upload_airbnb_csv': 'Upload Airbnb Reviews (CSV)',
    'manual_review_entry': 'Manual Review Entry',
    'always_available': 'Always Available',
    'manual_review_description': 'Manually add reviews from any platform or source.',
    'add_review_manually': 'Add Review Manually',
    'security_legal_considerations': 'Security & Legal Considerations',
    'api_keys_security': 'API Keys:',
    'api_keys_security_description': 'All API keys are stored securely using Supabase Edge Functions and never exposed to the client.',
    'data_compliance': 'Data Compliance:',
    'data_compliance_description': 'We only collect review data you have legitimate access to as a property owner/manager.',
    'terms_service_description': 'Always respect platform Terms of Service. We do not support or recommend unauthorized data scraping.',
    'data_privacy_description': 'Guest review data is handled according to GDPR and privacy best practices.',
    // Toast messages
    'missing_information': 'Missing Information',
    'provide_api_key_place_id': 'Please provide both API key and Place ID',
    'review_limit_reached': 'Review Limit Reached',
    'review_limit_reached_description': 'You\'ve reached your',
    'review_limit_plan_text': 'review limit on the Free plan. Upgrade to Pro for unlimited reviews.',
    'google_reviews_imported': 'Google Reviews Imported',
    'successfully_imported_google_reviews': 'Successfully imported',
    'reviews_from_google': 'reviews from Google Places',
    'connection_failed': 'Connection Failed',
    'failed_connect_google': 'Failed to connect to Google Places API',
    'no_file_selected': 'No File Selected',
    'select_csv_file': 'Please select a CSV file to import',
    'booking_reviews_imported': 'Booking.com Reviews Imported',
    'successfully_imported_csv_reviews': 'Successfully imported',
    'reviews_from_csv': 'reviews from CSV',
    'import_failed': 'Import Failed',
    'failed_import_csv': 'Failed to import CSV file',
    'airbnb_reviews_imported': 'Airbnb Reviews Imported'
  },
  el: {
    'guest_review_manager': 'Διαχείριση Κριτικών Επισκεπτών',
    'home': 'Αρχική',
    'reviews': 'Κριτικές',
    'settings': 'Ρυθμίσεις',
    'contact': 'Επικοινωνία',
    'sign_out': 'Αποσύνδεση',
    'error_signing_out': 'Σφάλμα κατά την αποσύνδεση',
    'signed_out_successfully': 'Επιτυχής αποσύνδεση',
    'logged_out_message': 'Έχετε αποσυνδεθεί.',
    'contact_title': 'Επικοινωνήστε μαζί μας για ερωτήσεις, υποστήριξη και ευκαιρίες συνεργασίας',
    'hotel_group_name': 'Όνομα Ξενοδοχείου / Ομίλου',
    'enter_hotel_name': 'Εισάγετε το όνομα του Ξενοδοχείου ή Ομίλου σας',
    'full_name': 'Πλήρες Όνομα',
    'enter_full_name': 'Εισάγετε το πλήρες όνομα',
    'email': 'Email',
    'enter_work_email': 'Εισάγετε το επαγγελματικό σας Email',
    'work_phone': 'Τηλέφωνο Εργασίας',
    'enter_work_phone': 'Εισάγετε το τηλέφωνο εργασίας σας',
    'message': 'Μήνυμα',
    'enter_message': 'Εισάγετε το μήνυμά σας...',
    'contact_us': 'Επικοινωνήστε Μαζί Μας',
    'representative_offices': 'Επικοινωνήστε με τα αντιπροσωπευτικά μας γραφεία παγκοσμίως',
    'message_sent': 'Το Μήνυμα Στάλθηκε',
    'message_sent_description': 'Σας ευχαριστούμε που επικοινωνήσατε μαζί μας. Θα επικοινωνήσουμε σύντομα!',
    // Dashboard
    'dashboard_title': 'Πίνακας Κριτικών Επισκεπτών',
    'dashboard_subtitle': 'Επισκόπηση των πρόσφατων κριτικών και απόδοσής σας',
    'total_reviews': 'Συνολικές Κριτικές',
    'average_rating': 'Μέση Βαθμολογία',
    'pending_replies': 'Εκκρεμείς Απαντήσεις',
    'platform_distribution': 'Κατανομή Πλατφόρμας',
    'recent_reviews': 'Πρόσφατες Κριτικές',
    'view_all_reviews': 'Δείτε όλες τις κριτικές',
    // Reviews
    'reviews_title': 'Κριτικές Επισκεπτών',
    'reviews_subtitle': 'Διαχειριστείτε και απαντήστε σε όλες τις κριτικές σας',
    'search_reviews': 'Αναζήτηση κριτικών...',
    'filter_by_platform': 'Φιλτράρισμα κατά πλατφόρμα',
    'filter_by_rating': 'Φιλτράρισμα κατά βαθμολογία',
    'all_platforms': 'Όλες οι πλατφόρμες',
    'all_ratings': 'Όλες οι βαθμολογίες',
    'reply': 'Απάντηση',
    'replied': 'Απαντήθηκε',
    // Analytics
    'analytics_title': 'Αναλυτικά',
    'analytics_subtitle': 'Πληροφορίες και τάσεις από τις κριτικές των επισκεπτών σας',
    'review_trends': 'Τάσεις Κριτικών',
    'rating_distribution': 'Κατανομή Βαθμολογίας',
    'sentiment_analysis': 'Ανάλυση Συναισθήματος',
    'keyword_analysis': 'Ανάλυση Λέξεων-Κλειδιών',
    'positive_keywords': 'Περισσότερο Αναφερόμενες Θετικές Λέξεις',
    'negative_keywords': 'Περισσότερο Αναφερόμενες Αρνητικές Λέξεις',
    'positive': 'Θετικό',
    'negative': 'Αρνητικό',
    'neutral': 'Ουδέτερο',
    // Settings
    'settings_title': 'Ρυθμίσεις',
    'settings_subtitle': 'Διαχειριστείτε τον λογαριασμό και τις ενσωματώσεις πλατφόρμας σας',
    'notification_settings': 'Ρυθμίσεις Ειδοποιήσεων',
    'new_reviews': 'Νέες κριτικές',
    'low_ratings': 'Χαμηλές βαθμολογίες (3 αστέρια ή λιγότερα)',
    'reply_reminders': 'Υπενθυμίσεις απάντησης',
    'weekly_reports': 'Εβδομαδιαίες αναφορές',
    'connect': 'Σύνδεση',
    'disconnect': 'Αποσύνδεση',
    'last_sync': 'Τελευταίος συγχρονισμός',
    'never': 'Ποτέ',
    'connected': 'Συνδεδεμένο',
    'not_connected': 'Μη συνδεδεμένο',
    // Login
    'sign_in': 'Σύνδεση',
    'sign_up': 'Εγγραφή',
    'create_account': 'Δημιουργήστε τον λογαριασμό σας',
    'welcome_back': 'Καλώς ήρθατε πίσω',
    'sign_in_to_account': 'Συνδεθείτε στον λογαριασμό σας',
    'password': 'Κωδικός',
    'confirm_password': 'Επιβεβαίωση Κωδικού',
    'first_name': 'Όνομα',
    'last_name': 'Επώνυμο',
    'business_name': 'Όνομα Επιχείρησης',
    'optional': 'Προαιρετικό',
    'have_account': 'Έχετε ήδη λογαριασμό;',
    'no_account': 'Δεν έχετε λογαριασμό;',
    'sign_up_here': 'Εγγραφείτε εδώ',
    'sign_in_here': 'Συνδεθείτε εδώ',
    // Integrations
    'platform_integrations': 'Ενσωματώσεις Πλατφόρμας',
    'connect_review_platforms': 'Συνδέστε τις πλατφόρμες κριτικών σας για αυτόματη εισαγωγή κριτικών επισκεπτών.',
    'google_reviews': 'Κριτικές Google',
    'api_available': 'API Διαθέσιμο',
    'google_reviews_description': 'Συνδεθείτε στο Google Places API για αυτόματη λήψη κριτικών για την τοποθεσία της επιχείρησής σας.',
    'google_api_key': 'Κλειδί Google Places API',
    'enter_google_api_key': 'Εισάγετε το κλειδί Google Places API σας',
    'place_id': 'ID Τοποθεσίας',
    'enter_place_id': 'Εισάγετε το Google Place ID σας (π.χ., ChIJN1t_tDeuEmsRUsoyG83frY4)',
    'find_place_id_text': 'Βρείτε το Place ID σας χρησιμοποιώντας το',
    'google_place_id_finder': 'Google Place ID Finder',
    'fetching_reviews': 'Λήψη Κριτικών...',
    'fetch_google_reviews': 'Λήψη Κριτικών Google',
    'booking_reviews': 'Κριτικές Booking.com',
    'manual_import': 'Χειροκίνητη Εισαγωγή',
    'booking_description': 'Το Booking.com δεν παρέχει δημόσια APIs. Ανεβάστε τις κριτικές σας χειροκίνητα χρησιμοποιώντας εισαγωγή CSV.',
    'no_api_access': 'Χωρίς Πρόσβαση API:',
    'booking_restrictions': 'Το Booking.com περιορίζει την πρόσβαση σε δεδομένα κριτικών μόνο σε επίσημους συνεργάτες. Το web scraping παραβιάζει τους Όρους Χρήσης τους και μπορεί να οδηγήσει σε νομική δράση.',
    'upload_booking_csv': 'Ανεβάστε Κριτικές Booking.com (CSV)',
    'csv_format_expected': 'Αναμενόμενη μορφή: guest_name, date, rating, review_text',
    'importing': 'Εισάγεται...',
    'import_csv_file': 'Εισαγωγή Αρχείου CSV',
    'airbnb_reviews': 'Κριτικές Airbnb',
    'airbnb_description': 'Το Airbnb διέκοψε το δημόσιο API του. Χρησιμοποιήστε χειροκίνητη εισαγωγή ή ανέβασμα CSV από τον πίνακα ελέγχου σας.',
    'api_discontinued': 'API Διακοπή:',
    'airbnb_restrictions': 'Το Airbnb έκλεισε το δημόσιο API του το 2017. Η χειροκίνητη εξαγωγή δεδομένων από τον πίνακα ελέγχου είναι η μόνη νόμιμη επιλογή.',
    'upload_airbnb_csv': 'Ανεβάστε Κριτικές Airbnb (CSV)',
    'manual_review_entry': 'Χειροκίνητη Εισαγωγή Κριτικής',
    'always_available': 'Πάντα Διαθέσιμο',
    'manual_review_description': 'Προσθέστε χειροκίνητα κριτικές από οποιαδήποτε πλατφόρμα ή πηγή.',
    'add_review_manually': 'Προσθέστε Κριτική Χειροκίνητα',
    'security_legal_considerations': 'Ασφάλεια & Νομικές Εκτιμήσεις',
    'api_keys_security': 'Κλειδιά API:',
    'api_keys_security_description': 'Όλα τα κλειδιά API αποθηκεύονται με ασφάλεια χρησιμοποιώντας Supabase Edge Functions και δεν εκτίθενται ποτέ στον πελάτη.',
    'data_compliance': 'Συμμόρφωση Δεδομένων:',
    'data_compliance_description': 'Συλλέγουμε μόνο δεδομένα κριτικών στα οποία έχετε νόμιμη πρόσβαση ως ιδιοκτήτης/διαχειριστής ακινήτου.',
    'terms_service_description': 'Σεβαστείτε πάντα τους Όρους Χρήσης της πλατφόρμας. Δεν υποστηρίζουμε ή συνιστούμε μη εξουσιοδοτημένη εξόρυξη δεδομένων.',
    'data_privacy_description': 'Τα δεδομένα κριτικών επισκεπτών χειρίζονται σύμφωνα με το GDPR και τις βέλτιστες πρακτικές απορρήτου.',
    // Toast messages
    'missing_information': 'Ελλιπείς Πληροφορίες',
    'provide_api_key_place_id': 'Παρακαλώ παρέχετε και το κλειδί API και το Place ID',
    'review_limit_reached': 'Όριο Κριτικών Ξεπεράστηκε',
    'review_limit_reached_description': 'Έχετε φτάσει το όριό σας των',
    'review_limit_plan_text': 'κριτικών στο Δωρεάν πλάνο. Αναβαθμίστε στο Pro για απεριόριστες κριτικές.',
    'google_reviews_imported': 'Κριτικές Google Εισήχθησαν',
    'successfully_imported_google_reviews': 'Επιτυχής εισαγωγή',
    'reviews_from_google': 'κριτικών από το Google Places',
    'connection_failed': 'Αποτυχία Σύνδεσης',
    'failed_connect_google': 'Αποτυχία σύνδεσης στο Google Places API',
    'no_file_selected': 'Δεν Επιλέχθηκε Αρχείο',
    'select_csv_file': 'Παρακαλώ επιλέξτε ένα αρχείο CSV για εισαγωγή',
    'booking_reviews_imported': 'Κριτικές Booking.com Εισήχθησαν',
    'successfully_imported_csv_reviews': 'Επιτυχής εισαγωγή',
    'reviews_from_csv': 'κριτικών από CSV',
    'import_failed': 'Αποτυχία Εισαγωγής',
    'failed_import_csv': 'Αποτυχία εισαγωγής αρχείου CSV',
    'airbnb_reviews_imported': 'Κριτικές Airbnb Εισήχθησαν'
  },
  fr: {
    'guest_review_manager': 'Gestionnaire d\'Avis Client',
    'home': 'Accueil',
    'reviews': 'Avis',
    'settings': 'Paramètres',
    'contact': 'Contact',
    'sign_out': 'Se Déconnecter',
    'error_signing_out': 'Erreur lors de la déconnexion',
    'signed_out_successfully': 'Déconnexion réussie',
    'logged_out_message': 'Vous avez été déconnecté.',
    'contact_title': 'Contactez-nous pour des demandes, support et opportunités de partenariat',
    'hotel_group_name': 'Nom de l\'Hôtel / Groupe',
    'enter_hotel_name': 'Entrez le nom de votre Hôtel ou Groupe',
    'full_name': 'Nom Complet',
    'enter_full_name': 'Entrez le nom complet',
    'email': 'Email',
    'enter_work_email': 'Entrez votre Email professionnel',
    'work_phone': 'Téléphone Professionnel',
    'enter_work_phone': 'Entrez votre numéro de téléphone professionnel',
    'message': 'Message',
    'enter_message': 'Entrez votre message...',
    'contact_us': 'Nous Contacter',
    'representative_offices': 'Contactez nos bureaux représentatifs dans le monde entier',
    'message_sent': 'Message Envoyé',
    'message_sent_description': 'Merci de nous avoir contactés. Nous vous répondrons bientôt!'
  },
  de: {
    'guest_review_manager': 'Gästebewertungs-Manager',
    'home': 'Startseite',
    'reviews': 'Bewertungen',
    'settings': 'Einstellungen',
    'contact': 'Kontakt',
    'sign_out': 'Abmelden',
    'error_signing_out': 'Fehler beim Abmelden',
    'signed_out_successfully': 'Erfolgreich abgemeldet',
    'logged_out_message': 'Sie wurden abgemeldet.',
    'contact_title': 'Kontaktieren Sie uns für Anfragen, Support und Partnerschaftsmöglichkeiten',
    'hotel_group_name': 'Hotel / Gruppen Name',
    'enter_hotel_name': 'Geben Sie Ihren Hotel- oder Gruppennamen ein',
    'full_name': 'Vollständiger Name',
    'enter_full_name': 'Vollständigen Namen eingeben',
    'email': 'Email',
    'enter_work_email': 'Geben Sie Ihre Geschäfts-Email ein',
    'work_phone': 'Arbeitstelefon',
    'enter_work_phone': 'Geben Sie Ihre Arbeitstelefonnummer ein',
    'message': 'Nachricht',
    'enter_message': 'Geben Sie Ihre Nachricht ein...',
    'contact_us': 'Kontaktieren Sie Uns',
    'representative_offices': 'Wenden Sie sich an unsere Vertretungsbüros weltweit',
    'message_sent': 'Nachricht Gesendet',
    'message_sent_description': 'Vielen Dank, dass Sie uns kontaktiert haben. Wir werden uns bald bei Ihnen melden!'
  },
  zh: {
    'guest_review_manager': '客户评价管理器',
    'home': '首页',
    'reviews': '评价',
    'settings': '设置',
    'contact': '联系',
    'sign_out': '登出',
    'error_signing_out': '登出时出错',
    'signed_out_successfully': '成功登出',
    'logged_out_message': '您已登出。',
    'contact_title': '联系我们获取咨询、支持和合作机会',
    'hotel_group_name': '酒店/集团名称',
    'enter_hotel_name': '输入您的酒店或集团名称',
    'full_name': '全名',
    'enter_full_name': '输入全名',
    'email': '邮箱',
    'enter_work_email': '输入您的工作邮箱',
    'work_phone': '工作电话',
    'enter_work_phone': '输入您的工作电话号码',
    'message': '消息',
    'enter_message': '输入您的消息...',
    'contact_us': '联系我们',
    'representative_offices': '联系我们在全球的代表处',
    'message_sent': '消息已发送',
    'message_sent_description': '感谢您联系我们。我们将很快回复您！'
  },
  ar: {
    'guest_review_manager': 'مدير تقييمات الضيوف',
    'home': 'الرئيسية',
    'reviews': 'التقييمات',
    'settings': 'الإعدادات',
    'contact': 'اتصل بنا',
    'sign_out': 'تسجيل الخروج',
    'error_signing_out': 'خطأ في تسجيل الخروج',
    'signed_out_successfully': 'تم تسجيل الخروج بنجاح',
    'logged_out_message': 'تم تسجيل خروجك.',
    'contact_title': 'اتصل بنا للاستفسارات والدعم وفرص الشراكة',
    'hotel_group_name': 'اسم الفندق / المجموعة',
    'enter_hotel_name': 'أدخل اسم الفندق أو المجموعة',
    'full_name': 'الاسم الكامل',
    'enter_full_name': 'أدخل الاسم الكامل',
    'email': 'البريد الإلكتروني',
    'enter_work_email': 'أدخل بريدك الإلكتروني للعمل',
    'work_phone': 'هاتف العمل',
    'enter_work_phone': 'أدخل رقم هاتف العمل',
    'message': 'الرسالة',
    'enter_message': 'أدخل رسالتك...',
    'contact_us': 'اتصل بنا',
    'representative_offices': 'تواصل مع مكاتبنا التمثيلية حول العالم',
    'message_sent': 'تم إرسال الرسالة',
    'message_sent_description': 'شكراً لتواصلك معنا. سنرد عليك قريباً!'
  },
  ja: {
    'guest_review_manager': 'ゲストレビューマネージャー',
    'home': 'ホーム',
    'reviews': 'レビュー',
    'settings': '設定',
    'contact': 'お問い合わせ',
    'sign_out': 'ログアウト',
    'error_signing_out': 'ログアウト時にエラーが発生しました',
    'signed_out_successfully': 'ログアウトしました',
    'logged_out_message': 'ログアウトしました。',
    'contact_title': 'お問い合わせ、サポート、パートナーシップの機会についてご連絡ください',
    'hotel_group_name': 'ホテル/グループ名',
    'enter_hotel_name': 'ホテルまたはグループ名を入力してください',
    'full_name': 'フルネーム',
    'enter_full_name': 'フルネームを入力してください',
    'email': 'メール',
    'enter_work_email': '仕事用メールアドレスを入力してください',
    'work_phone': '勤務先電話',
    'enter_work_phone': '勤務先の電話番号を入力してください',
    'message': 'メッセージ',
    'enter_message': 'メッセージを入力してください...',
    'contact_us': 'お問い合わせ',
    'representative_offices': '世界各地の代表事務所にお問い合わせください',
    'message_sent': 'メッセージが送信されました',
    'message_sent_description': 'お問い合わせありがとうございます。すぐに返信いたします！'
  }
};

interface LanguageProviderProps {
  children: React.ReactNode;
}

export const LanguageProvider: React.FC<LanguageProviderProps> = ({ children }) => {
  const [currentLanguage, setCurrentLanguage] = useState('en');

  const setLanguage = (languageCode: string) => {
    setCurrentLanguage(languageCode);
  };

  const t = (key: string): string => {
    return translations[currentLanguage as keyof typeof translations]?.[key as keyof typeof translations.en] || key;
  };

  const value = {
    currentLanguage,
    setLanguage,
    t,
  };

  return <LanguageContext.Provider value={value}>{children}</LanguageContext.Provider>;
};